package com.assistant.archie.feature.memory

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Spec 14 §4.1 / §7 B-07 DoD: `MemoryLinkResolver` over **every link form found in context/memory
 * — 468 real (file, href) pairs from the 138 files of the live tree (memory-links.tsv, generated by
 * gen_links.py with an independent reference of MEM-2) — plus the edge cases the fixture lacks.
 */
class MemoryLinkResolverTest {
    private val known = filePaths(MemoryFixtures.liveTree)

    @Test fun `fixture is the real corpus`() {
        val links = MemoryFixtures.links
        assertTrue("expected the full corpus, got ${links.size}", links.size >= 400)
        assertEquals(138, known.size)
        // Every kind the resolver distinguishes occurs in real memory files.
        assertEquals(setOf("memory", "external", "outside", "backend"), links.map { it.kind }.toSet())
    }

    @Test fun `every real memory link resolves like MEM-2 says`() {
        val failures = MemoryFixtures.links.mapNotNull { c ->
            val got = MemoryLinkResolver.resolve(c.from, c.href)
            val expected: MemoryLink = when (c.kind) {
                "memory" -> MemoryLink.Document(c.target, c.fragment.ifEmpty { null })
                "external" -> inApp(c.target) ?: MemoryLink.External(c.target)
                "anchor" -> MemoryLink.Anchor(c.target)
                // What MEM-2 leaves to the server is then subject to the internal-link rules (§9.4).
                "backend", "outside" -> inApp(c.target) ?: MemoryLink.Server(c.target)
                else -> error("unknown kind ${c.kind}")
            }
            if (got == expected) null else "${c.from} → ${c.href}: expected $expected, got $got"
        }
        assertTrue(failures.take(20).joinToString("\n"), failures.isEmpty())
    }

    @Test fun `tree membership of resolved documents matches the live tree`() {
        val failures = MemoryFixtures.links.filter { it.kind == "memory" }.mapNotNull { c ->
            val path = (MemoryLinkResolver.resolve(c.from, c.href) as MemoryLink.Document).path
            val inTree = path in known
            if (inTree == (c.inTree == "true")) null else "${c.from} → ${c.href}: inTree=$inTree"
        }
        assertTrue(failures.joinToString("\n"), failures.isEmpty())
        // The corpus contains dangling links (examples in INDEX.md), which drive "Not found: … / Open anyway".
        assertTrue(MemoryFixtures.links.any { it.kind == "memory" && it.inTree == "false" })
    }

    @Test fun `relative, dot and dot-dot links resolve against the current folder`() {
        val cur = "assistant/architecture/voice_subsystem.md"
        assertEquals(MemoryLink.Document("assistant/architecture/wakeword_subsystem.md"), MemoryLinkResolver.resolve(cur, "wakeword_subsystem.md"))
        assertEquals(MemoryLink.Document("assistant/architecture/x.md"), MemoryLinkResolver.resolve(cur, "./x.md"))
        assertEquals(MemoryLink.Document("assistant/infrastructure/ssh.md", "setup"), MemoryLinkResolver.resolve(cur, "../infrastructure/ssh.md#setup"))
        assertEquals(MemoryLink.Document("rodrigo/ctx.md"), MemoryLinkResolver.resolve(cur, "../../rodrigo/ctx.md"))
        assertEquals(MemoryLink.Document("MEMORY.md"), MemoryLinkResolver.resolve(cur, "/memory/MEMORY.md"))
    }

    @Test fun `percent-encoded segments are decoded`() {
        assertEquals(MemoryLink.Document("projects/my notes.md"), MemoryLinkResolver.resolve("projects/a.md", "my%20notes.md"))
    }

    @Test fun `escaping the root is not a memory document and opens on the server`() {
        assertEquals(MemoryLink.Server("/AGENTS.md"), MemoryLinkResolver.resolve("assistant/plans/x.md", "../../../AGENTS.md"))
        assertEquals(MemoryLink.Server("/api/app.py"), MemoryLinkResolver.resolve("assistant/utilities/x.md", "../../../../api/app.py"))
    }

    @Test fun `anchors, schemes and site paths`() {
        assertEquals(MemoryLink.Anchor("lifecycle"), MemoryLinkResolver.resolve("a.md", "#lifecycle"))
        assertEquals(MemoryLink.External("https://github.com/x"), MemoryLinkResolver.resolve("a.md", "https://github.com/x"))
        assertEquals(MemoryLink.External("mailto:me@example.com"), MemoryLinkResolver.resolve("a.md", "mailto:me@example.com"))
        assertEquals(MemoryLink.External("//cdn.example.com/x.md"), MemoryLinkResolver.resolve("a.md", "//cdn.example.com/x.md"))
        assertEquals(MemoryLink.Server("/uploads/a.png"), MemoryLinkResolver.resolve("a.md", "/uploads/a.png"))
        assertEquals(MemoryLink.Server("/memory/p/v.mp4#t=10"), MemoryLinkResolver.resolve("p/a.md", "/memory/p/v.mp4#t=10"))
    }

    @Test fun `internal links (spec 12 section 9-4) open in the app`() {
        val ctx = com.assistant.core.markdown.InternalLinks.Context("https://192.168.0.200")
        assertEquals(MemoryLink.Document("a.md"), MemoryLinkResolver.resolve("p/b.md", "/markdown_reader.html?file=memory/a.md", ctx))
        assertEquals(MemoryLink.Visual("avatar-pipeline/index.html"), MemoryLinkResolver.resolve("p/b.md", "https://192.168.0.200/avatar-pipeline/", ctx))
        assertEquals(MemoryLink.Visual("visualizations/x.html"), MemoryLinkResolver.resolve("p/b.md", "/visualizations/x.html", ctx))
        assertEquals(MemoryLink.Document("projects/x.md"), MemoryLinkResolver.resolve("p/b.md", "https://192.168.0.200/memory/projects/x.md", ctx))
        // An explicit relative markdown link is MEM-2 (relative to this file, like the web)...
        assertEquals(MemoryLink.Document("p/docs/x.md"), MemoryLinkResolver.resolve("p/b.md", "docs/x.md", ctx))
        // ...while an auto-linked printed path carries its canonical URL and lands on the docs file.
        val auto = com.assistant.core.markdown.autoLinkPaths(listOf(com.assistant.core.markdown.MdInline.Code("docs/specs/x.md")))
        val href = (auto.single() as com.assistant.core.markdown.MdInline.Link).href
        assertEquals(MemoryLink.Document("archie/specs/x.md"), MemoryLinkResolver.resolve("p/b.md", href, ctx))
        assertEquals(MemoryLink.External("https://example.com/x.html"), MemoryLinkResolver.resolve("p/b.md", "https://example.com/x.html", ctx))
    }

    @Test fun `raw file URL encodes every segment`() {
        assertEquals("/memory/projects/my%20notes%23v2.md", MemoryLinkResolver.memoryFileUrl("projects/my notes#v2.md"))
        assertEquals("/memory/MEMORY.md", MemoryLinkResolver.memoryFileUrl("/MEMORY.md"))
    }

    private fun inApp(href: String): MemoryLink? = when (val t = com.assistant.core.markdown.InternalLinks.resolve(href)) {
        is com.assistant.core.markdown.InternalLinks.Target.Memory -> MemoryLink.Document(t.path, t.fragment)
        is com.assistant.core.markdown.InternalLinks.Target.Visual -> MemoryLink.Visual(t.path)
        null -> null
    }
}
